version: "3.9"

services:
  dominionsark-api:
    image: alpine:latest
    container_name: dominionsark-api
    command: ["sh", "-c", "while true; do echo '👑 Dominion Ark Baby is alive with secrets loaded'; sleep 30; done"]
    restart: always
