from fpdf import FPDF

class Blueprint(FPDF):
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, 'Dominion Healing | dominionhealing.org | Page ' + str(self.page_no()), align='C')

pdf = Blueprint('P', 'mm', 'A4')
pdf.set_auto_page_break(auto=True, margin=22)
pdf.set_margins(15, 15, 15)
W = 180

def heading(text, size=13):
    pdf.set_font('Helvetica', 'B', size)
    pdf.multi_cell(W, 9, text)
    pdf.ln(2)

def body(text):
    pdf.set_font('Helvetica', '', 11)
    pdf.multi_cell(W, 7, text)
    pdf.ln(3)

def rule():
    y = pdf.get_y()
    pdf.set_draw_color(180, 180, 180)
    pdf.line(15, y, 195, y)
    pdf.ln(6)

# Cover
pdf.add_page()
pdf.ln(30)
pdf.set_font('Helvetica', 'B', 30)
pdf.cell(W, 16, 'DIVINE SOVEREIGNTY', align='C')
pdf.ln(16)
pdf.cell(W, 16, 'BLUEPRINT', align='C')
pdf.ln(20)
pdf.set_font('Helvetica', '', 16)
pdf.cell(W, 10, 'Break Free. Heal Your Mindset. Build Your Empire.', align='C')
pdf.ln(14)
pdf.set_font('Helvetica', 'I', 12)
pdf.cell(W, 8, 'by Dominion Healing', align='C')
pdf.ln(8)
pdf.cell(W, 8, 'dominionhealing.org', align='C')
pdf.ln(40)
rule()
pdf.set_font('Helvetica', '', 10)
pdf.cell(W, 8, 'Value: $47  |  Your license: unlimited personal use', align='C')

# Intro + Ch1
pdf.add_page()
heading('INTRODUCTION: THE SOVEREIGNTY DECISION', 16)
rule()
body('Most people spend their entire lives waiting for permission. Permission to be great. Permission to earn more. Permission to live on their own terms.')
body('This blueprint is not for most people.')
body('This guide is for the ones who have already made the decision. The sovereignty decision. The moment you chose to stop being a passenger in your own life and start being the pilot.')
body('Divine Sovereignty is not a concept. It is a state of being. It is the alignment of your mindset, your systems, and your actions with the life you were created to live.')
body('What you hold in your hands right now is a battle-tested framework built from real results, real failures, and real breakthroughs. Follow it. Execute relentlessly.')
pdf.ln(5)
heading('CHAPTER 1: THE SOVEREIGNTY MINDSET', 16)
rule()
heading('1.1 Identify Your Limiting Programs')
body('Your mind runs programs installed before age 7. Most of them do not belong to you. They were handed to you by parents, teachers, and society. People who were also running borrowed programs.')
body('Exercise: Write down 5 beliefs you have about money. Now trace each one. Who gave it to you? If you cannot connect it to a result you consciously chose, delete it.')
heading('1.2 The Identity Shift Protocol')
body('You cannot out-earn your self-image. Before you build the business, you must become the person who runs that business.')
body('Daily Practice: Every morning, state your identity out loud. "I am a sovereign builder. I create value. I generate wealth. I walk in divine authority over my finances, my time, and my destiny."')
heading('1.3 Eliminating Scarcity Loops')
body('Scarcity is not a circumstance. It is a thought pattern that creates circumstances. Break the loop: every time a scarcity thought appears, replace it with an abundance action, even a small one.')
body('Start small. Pay a bill early. Give something away. Buy something you have been delaying. Each act reprograms the loop at a subconscious level.')

# Ch2
pdf.add_page()
heading('CHAPTER 2: REVENUE SYSTEM ARCHITECTURE', 16)
rule()
heading('2.1 The Four Revenue Pillars')
body('Pillar 1 - Digital Products: Knowledge packaged and sold. High margin, zero inventory. This blueprint is an example. One creation, infinite sales.')
body('Pillar 2 - Automated Content: YouTube, TikTok, email sequences. Content that earns while you sleep. The key is production systems, not inspiration.')
body('Pillar 3 - Market Participation: Trading systems with defined rules. OANDA for forex, Binance for crypto. Risk management is the skill. Entry and exit is just execution.')
body('Pillar 4 - Service Leverage: Your expertise delivered systematically. Email campaigns. Lead generation funnels. Not trading hours for dollars, trading systems for revenue.')
heading('2.2 Stack the Pillars')
body('Do not chase one source. Sovereign builders stack sources. Pillar 1 funds Pillar 2. Pillar 2 grows the audience for Pillar 1. Pillar 3 creates capital for Pillar 4. They compound.')
body('Rule: Do not move to Pillar 2 until Pillar 1 generates at least one sale per week. Proof of concept before scale.')
heading('2.3 The Automation Threshold')
body('Every task you do manually is a system waiting to be built. Track everything you do in a week. Circle the repeatable tasks. Build a process for each one.')
body('Tools: n8n for automation workflows. Brevo for email. Gumroad for product delivery. Your goal is a stack that runs without your daily attention.')

# Ch3
pdf.add_page()
heading('CHAPTER 3: THE 30-DAY EMPIRE SPRINT', 16)
rule()
heading('Week 1: Foundation (Days 1-7)')
body('Days 1-3: Identity audit. Complete the limiting programs exercise from Chapter 1. Write your sovereignty statement. Post it where you see it every single day.')
body('Days 4-7: Map your revenue architecture. Which of the four pillars fits your current skills? Start with one. Do not diversify until that pillar is producing revenue.')
heading('Week 2: Build (Days 8-14)')
body('Days 8-10: Create your first digital product. A guide, a template, a mini-course. Price it between $27 and $97. Keep it focused. Solve one specific problem for one specific person.')
body('Days 11-14: Set up your distribution. Gumroad for the product. Email list for the audience. One social channel for traffic. Focus your energy.')
heading('Week 3: Launch (Days 15-21)')
body('Days 15-17: Soft launch to your existing network. Get 3 sales minimum. These are proof of concept, not vanity metrics. Three real people paid real money. That is a business.')
body('Days 18-21: Iterate. Add a bonus. Tighten the sales description. Improve the cover image. Every iteration compounds.')
heading('Week 4: Scale (Days 22-30)')
body('Days 22-25: Build one automation. An email welcome sequence. Scheduled social posts. A system that works without your daily attention.')
body('Days 26-30: Review everything. What produced results? Double down on that single thing. Cut what did not move the needle. Then plan Month 2.')

# Ch4 + close
pdf.add_page()
heading('CHAPTER 4: DIVINE AUTHORITY IN EXECUTION', 16)
rule()
body('Sovereignty is not given. It is taken through daily decisions compounded over time.')
body('The difference between the person who reads this and the person who builds an empire from it is not intelligence. It is not resources. It is not timing.')
body('It is execution without permission.')
body('You do not need validation. You do not need perfect conditions. You do not need the full plan before you start.')
body('You need the next step. Then the one after that.')
body('Move with divine confidence. Build with divine patience. Execute with divine precision.')
body('The empire is not coming. You are already building it.')
pdf.ln(8)
rule()
heading('YOUR NEXT STEPS', 14)
body('1. Complete the identity audit from Chapter 1 today. Not this week. Today.')
body('2. Choose your primary revenue pillar and write a 30-day income target.')
body('3. Begin the 30-Day Empire Sprint tomorrow morning.')
body('4. Visit dominionhealing.org for community, tools, and systems.')
pdf.ln(6)
body('You invested $47 in this blueprint. Invest 30 days of execution and watch the return compound.')
pdf.ln(4)
body('Walk in divine power, wisdom, and sovereignty.')
pdf.set_font('Helvetica', 'B', 11)
pdf.cell(W, 8, 'Dominion Healing')

pdf.output('/tmp/divine-sovereignty-blueprint.pdf')
import os
sz = os.path.getsize('/tmp/divine-sovereignty-blueprint.pdf')
print(f'PDF generated: {sz} bytes, {pdf.page} pages')
