name: Baby CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Deploy Baby
        run: |
          echo "👑 Starting Baby deployment..."
          docker-compose up -d --build

      - name: Test Baby API
        run: |
          echo "👑 Testing Baby API..."
          curl --fail http://localhost:8080/
          echo "👑 Baby API responded OK — empire is live"
