name: Baby CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build & Start Baby
      env:
        YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
        YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        GUMROAD_TOKEN: ${{ secrets.GUMROAD_TOKEN }}
        OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
        OANDA_ACCOUNT_ID: ${{ secrets.OANDA_ACCOUNT_ID }}
        BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
        BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
        BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
        TIKTOK_CLIENT_ID: ${{ secrets.TIKTOK_CLIENT_ID }}
        TIKTOK_CLIENT_SECRET: ${{ secrets.TIKTOK_CLIENT_SECRET }}
      run: |
        echo "👑 Starting Baby deployment..."
        docker-compose up -d --build

    - name: Wait for API health (retries)
      run: |
        for i in {1..15}; do
          if curl -sSf http://localhost:8080/ >/dev/null; then
            echo "👑 API is healthy"; exit 0
          fi
          echo "Waiting for API... ($i/15)"
          sleep 6
        done
        echo "API did not become healthy in time"; exit 1

    - name: Probe revenue integrations (best-effort)
      continue-on-error: true
      run: |
        echo "👑 /gumroad";  curl --max-time 25 --silent --show-error http://localhost:8080/gumroad || true
        echo "👑 /youtube";  curl --max-time 25 --silent --show-error http://localhost:8080/youtube || true
        echo "👑 /oanda";    curl --max-time 25 --silent --show-error http://localhost:8080/oanda || true
        echo "👑 /binance";  curl --max-time 25 --silent --show-error http://localhost:8080/binance || true
        echo "👑 Baby deployed successfully!"

    - name: Check Dominion Web
      run: |
        for i in {1..10}; do
          if curl -sSf http://localhost/health >/dev/null; then
            echo "👑 Dominion Healing site is live"; exit 0
          fi
          echo "Waiting for dominion-web... ($i/10)"
          sleep 3
        done
        echo "dominion-web not reachable"; exit 1
