name: Baby CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and Deploy Baby
      env:
        YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
        YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        GUMROAD_TOKEN: ${{ secrets.GUMROAD_TOKEN }}
        OANDA_API_KEY: ${{ secrets.OANDA_API_KEY }}
        OANDA_ACCOUNT_ID: ${{ secrets.OANDA_ACCOUNT_ID }}
        BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
        BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
        BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
        TIKTOK_CLIENT_ID: ${{ secrets.TIKTOK_CLIENT_ID }}
        TIKTOK_CLIENT_SECRET: ${{ secrets.TIKTOK_CLIENT_SECRET }}
      run: |
        echo "👑 Starting Baby deployment..."
        docker-compose -f docker-compose.yml up -d --build
        echo "👑 Baby deployed successfully!"
