name: Baby CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -e
            echo "👑 Pulling latest code on VM..."
            cd ~/desktop-tutorial
            git fetch --all
            git reset --hard origin/main

            echo "👑 Restarting Docker stack..."
            docker compose down -v || true
            docker compose up -d --build

            echo "👑 Testing Baby API..."
            curl -s http://localhost:8080/ || true

            echo "👑 Testing Dominion Healing site..."
            curl -s http://localhost/health || true
