name: Empire Status Snapshot
on:
  schedule: [{ cron: "*/30 * * * *" }]
  workflow_dispatch:
jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Smoke test gateway
        env:
          GATEWAY: ${{ secrets.N8N_AGENT_GATEWAY_URL }}
          N8N_TOOL_SECRET: ${{ secrets.N8N_TOOL_SECRET }}
        run: |
          # Enable strict shell options for better error handling
          set -euo pipefail

          # Validate that GATEWAY is set and non-empty
          if [ -z "${GATEWAY:-}" ]; then
            echo "ERROR: GATEWAY environment variable is not set or is empty"
            exit 1
          fi

          # Validate that URL begins with http:// or https://
          if [[ ! "$GATEWAY" =~ ^https?:// ]]; then
            echo "ERROR: GATEWAY must begin with http:// or https://, got: ${GATEWAY:0:20}..."
            exit 1
          fi

          # Print the GATEWAY value for debugging (will be masked by GitHub if it's a secret)
          echo "Using GATEWAY='${GATEWAY}'"

          # Call curl with proper quoting and recommended flags
          curl --fail --show-error --location --max-time 10 -X POST "${GATEWAY}" \
            -H "X-AGENT-KEY: ${N8N_TOOL_SECRET}" -H "Content-Type: application/json" \
            -d '{"tool":"roi_snapshot","args":{"since":"7d","metrics":["revenue","orders"]}}' > snapshot.json
          echo "Result:" && cat snapshot.json
      - name: Append to Session Notes
        run: |
          ts=$(date -u +"%Y-%m-%d %H:%M:%SZ")
          echo "- $ts cron snapshot run" | cat - ops/SESSION_NOTES.md > ops/.tmp && mv ops/.tmp ops/SESSION_NOTES.md
      - name: Commit notes
        run: |
          git config user.name "empire-bot"
          git config user.email "bot@users.noreply.github.com"
          git add ops/SESSION_NOTES.md
          git commit -m "cron: snapshot note" || echo "no changes"
          git push
